[workspace]
members = ["crates/*"]

[workspace.dependencies]
ecow = { version = "0.2.3", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
owo-colors = "4.1"
miette = "7.4.0"


[package]
name = "kola"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
miette = { version = "7.4.0", features = ["fancy"] }
owo-colors.workspace = true
kola-print = { path = "crates/kola-print" }
kola-core = { path = "crates/kola-core" }
kola-tree = { path = "crates/kola-tree" }
