[package]
name = "kola"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
miette = { version = "7.4.0", features = ["fancy"] }
thiserror = "2.0"
chumsky = { version = "=1.0.0-alpha.7", features = [
    "label",
    "nightly",
    "unstable",
] }
ecow = "0.2.3"
# indexmap = "2.7.0"
