[package]
name = "kola"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
miette = { version = "7.4.0", features = ["fancy"] }
thiserror = "2.0"
chumsky = { version = "=1.0.0-alpha.7", features = [
    "label",
    "nightly",
    "unstable",
    "serde",
] }
ecow = { version = "0.2.3", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
owo-colors = "4.1"
bumpalo = { version = "3", features = ["allocator_api", "collections"] }
# bump-scope = { version = "0.16.0", features = ["nightly-allocator-api"] }
