[workspace]
members = ["crates/*"]

[workspace.dependencies]
kola-print = { path = "crates/kola-print" }
kola-tree = { path = "crates/kola-tree" }
kola-syntax = { path = "crates/kola-syntax" }
kola-utils = { path = "crates/kola-utils" }
kola-semantic = { path = "crates/kola-semantic" }
kola-compiler = { path = "crates/kola-compiler" }
ecow = { version = "0.2.3", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
derive_more = { version = "2.0", features = ["from", "try_into", "display"] }
thiserror = "2.0"
owo-colors = "4.1"
miette = "7.4.0"
paste = "1.0"

[package]
name = "kola"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
miette = { version = "7.4.0", features = ["fancy"] }
owo-colors.workspace = true
kola-print.workspace = true
kola-tree.workspace = true
kola-syntax.workspace = true
kola-semantic.workspace = true
kola-compiler.workspace = true
