[package]
name = "kola-resolve"
version = "0.1.0"
edition = "2024"

[dependencies]
camino.workspace = true
kola-utils.workspace = true
kola-span.workspace = true
kola-tree.workspace = true
kola-syntax.workspace = true
indexmap.workspace = true
