[package]
name = "kola-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
kola-utils.workspace = true
kola-print.workspace = true
serde.workspace = true
derive_more.workspace = true
paste.workspace = true
# stacker = "0.1"                  # TODO use for visitor recursion
