[package]
name = "kola-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
kola-utils.workspace = true
kola-print.workspace = true
ecow.workspace = true
serde.workspace = true
owo-colors.workspace = true
derive_more.workspace = true
