[package]
name = "kola-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
camino.workspace = true
serde.workspace = true
thiserror.workspace = true
pathdiff = { version = "0.2.3", features = ["camino"] }
